In [1]:
# boosting algorithms 
# Ada boost
# gradient boosting
# XGboost

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r'C:\Users\dell\Desktop\diabetes.csv')

In [4]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [5]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [8]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [10]:
# scaling 
x = df.drop(['Glucose','BloodPressure','SkinThickness','Insulin','DiabetesPedigreeFunction'],axis=1)
y = df[['Glucose','BloodPressure','SkinThickness','Insulin','DiabetesPedigreeFunction']]

In [11]:
y.head()

Glucose  BloodPressure  SkinThickness  Insulin  DiabetesPedigreeFunction
0      148             72             35        0                     0.627
1       85             66             29        0                     0.351
2      183             64              0        0                     0.672
3       89             66             23       94                     0.167
4      137             40             35      168                     2.288

In [12]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

In [20]:
newx = minmax.fit_transform(y)

In [21]:
y = pd.DataFrame(newx,columns=['Glucose','BloodPressure','SkinThickness','Insulin','DiabetesPedigreeFunction'])

In [22]:
y.head()

Glucose  BloodPressure  SkinThickness   Insulin  DiabetesPedigreeFunction
0  0.743719       0.590164       0.353535  0.000000                  0.234415
1  0.427136       0.540984       0.292929  0.000000                  0.116567
2  0.919598       0.524590       0.000000  0.000000                  0.253629
3  0.447236       0.540984       0.232323  0.111111                  0.038002
4  0.688442       0.327869       0.353535  0.198582                  0.943638

In [48]:
df = pd.concat([y,x],axis=1)

In [49]:
df.head()

Outcome  Pregnancies   BMI  Age   Glucose  BloodPressure  SkinThickness  \
0        1            6  33.6   50  0.743719       0.590164       0.353535   
1        0            1  26.6   31  0.427136       0.540984       0.292929   
2        1            8  23.3   32  0.919598       0.524590       0.000000   
3        0            1  28.1   21  0.447236       0.540984       0.232323   
4        1            0  43.1   33  0.688442       0.327869       0.353535   

    Insulin  DiabetesPedigreeFunction  
0  0.000000                  0.234415  
1  0.000000                  0.116567  
2  0.000000                  0.253629  
3  0.111111                  0.038002  
4  0.198582                  0.943638

In [25]:
x = df.drop('Outcome',axis=1)
x1 = pd.DataFrame(x)
y = df['Outcome']
y1 = pd.DataFrame(y)

In [26]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test = train_test_split(x1,y1,test_size=0.25,random_state=42)


In [ ]:
# ada BOOSTER WITH CLASSIFICATION

In [30]:
from sklearn.ensemble import AdaBoostClassifier
ada_model = AdaBoostClassifier()
ada_model.fit(x1_train,y1_train)
y1_pred= ada_model.predict(x1_test)
y1_pred

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0], dtype=int64)

In [31]:
# validating 
from sklearn.metrics import accuracy_score
print("the ac score is:", accuracy_score(y1_test,y1_pred))

the ac score is: 0.7239583333333334


In [ ]:
# GRADIENT BOOSTING CLASSIFIER

In [33]:
from sklearn.ensemble import GradientBoostingClassifier
grd_model = GradientBoostingClassifier()
grd_model.fit(x1_train,y1_train)
y1_predga = grd_model.predict(x1_test)

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [34]:
print("the acc score is:" , accuracy_score(y1_test,y1_predga))

the acc score is: 0.7447916666666666


In [ ]:
#XGBOOST CLASSIFIER

In [44]:
pip install xgboost

  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/24/ec/ad387100fa3cc2b9b81af0829b5ecfe75ec5bb19dd7c19d4fea06fb81802/xgboost-2.0.3-py3-none-win_amd64.whl.metadata
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/99.8 MB 1.7 MB/s eta 0:01:01
   ---------------------------------------- 0.1/99.8 MB 1.3 MB/s eta 0:01:17
   ---------------------------------------- 0.3/99.8 MB 1.9 MB/s eta 0:00:53
   ---------------------------------------- 0.6/99.8 MB 3.2 MB/s eta 0:00:31
   ---------------------------------------- 1.2/99.8 MB 4.9 MB/s eta 0:00:21
    --------------------------------------- 2.3/99.8 MB 8.2 MB/s eta 0:00:12
   - -------------------------------------- 3.7/99.8 MB 10.6 MB/s eta 0:00:10
   -- ------------------------------------- 5.6/99.8 MB 15.0 MB/s eta 0:00:07
   --- ------------------------------------ 8.1/99.8 MB 19.2 MB/s eta 0:00:05
   ---- ---------------------

In [45]:

from xgboost import XGBClassifier
XG_model = XGBClassifier()
XG_model.fit(x1_train,y1_train)
y1_predxg = XG_model.predict(x1_test)

In [46]:
print("the acc score is:", accuracy_score(y1_test,y1_predxg))

the acc score is: 0.7135416666666666


In [50]:
df.head()

Outcome  Pregnancies   BMI  Age   Glucose  BloodPressure  SkinThickness  \
0        1            6  33.6   50  0.743719       0.590164       0.353535   
1        0            1  26.6   31  0.427136       0.540984       0.292929   
2        1            8  23.3   32  0.919598       0.524590       0.000000   
3        0            1  28.1   21  0.447236       0.540984       0.232323   
4        1            0  43.1   33  0.688442       0.327869       0.353535   

    Insulin  DiabetesPedigreeFunction  
0  0.000000                  0.234415  
1  0.000000                  0.116567  
2  0.000000                  0.253629  
3  0.111111                  0.038002  
4  0.198582                  0.943638

In [51]:
ada_model.predict([[6,	33.6,	50,	0.743719,	0.590164,	0.353535,	0.000000,	0.234415]])

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [52]:
XG_model.predict([[1,	26.6,	31,	0.427136,	0.540984,	0.292929,	0.000000,	0.116567]])

array([0])

In [53]:
grd_model.predict([[8,	23.3,	32,	0.919598,	0.524590,	0.000000,	0.000000,	0.253629]])

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)